name: jaspr_html_to_component
description: Convert any HTML String into Jaspr Components
version: 0.0.3
repository: https://github.com/AlissonMMenezes/jaspr_html_to_component

environment:
  sdk: ^3.5.1

# Add regular dependencies here.
dependencies:
  html: ^0.15.4
  jaspr: ^0.15.0
  jaspr_test: ^0.15.0
  # path: ^1.8.0

dev_dependencies:
  lints: ^4.0.0
  test: ^1.24.0
